language: node_js
node_js:
  - 'stable'
addons:
  code_climate:
    repo_token: d5ecf7e1cbdc5743de2316a68c72f7dec90a7f0de35c4f953fdf67ce8b237db7
after_success:
  - npm install codeclimate-test-reporter
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: myungsunrex@gmail.com
  api_key:
    secure: k3HIgRQgZgWoj3fmWu12oxasNpKuvcgcIc+9sjHalDl2PCOkX7pJUP+d60CyBh5RNCTY0yW0BRNTYJ2lLHK5twd/NgF1Y3UxRjU8zZR2cVWWMfyDLdp7QvRzkKYFZrmFPGm63f6Ys2CSAnrL8HiVMzyV8knIF47AnrHxiqLNrM6HYqTboqGdFh/1NNNV9zZoc3SteZucqjC9JT87sQ8zmBcIsstdN3YTNEyxEwpkZoiYPdlwE1ctt69Y6oZmJ72QhHdrymFRuv4Y7vdWFy90ZZbPtb9XKsHiGdOWdP9WPkHVooXnRI69imeGEKz0+sCs7w32EoinJNuH+piF/n01P89aEfQi9IhX2aJjGd2rJ5jo+8jJxWzy7q1Hg+1IHr+ztz8oePjXmpctfDYuSkqiSQ0f7uL/SQywiw19qxKbZGityxM+T2YfX+BxDjlmlDBvMOv0spVfuqeNrhqBb/JDthpK/lj/OADb1Il7qsEflGeDHYW5PMGYXY2KJVEcbvBbL4D/xCQvxXZmxfvplFlNIwgGnLIzLtBx8DOLrudfkJiQllZqxNpR8voEQ6jO38lzax3OVLv72LYOUxbIr0Jr7Ij+pWZ26HqPvz53wr93Zn/JoFn4AbYvXQpt49vCzFc4FVsKA9m4dYo9IhzQcizK/oYEm1tfsYtHdMauvJFOQoQ=
  on:
    tags: true
    repo: rexk/mocha-mix-jsdom
